version: "3.8"
services:
  bot:
    build: ./src/bot
    ports:
      - "8001:8001"
    depends_on:
      - database
      - client
  client:
    build: ./src/client
    ports:
      - "8002:8002"
      - "3000:3000"
    depends_on:
      - database
  database:
    build: ./src/database
    ports:
      - "8000:8000"
  website:
    build: ./src/website
    ports:
      - "3001:3001"
