version: "3.8"
services:
  bot:
    build: ./src/bot
    ports:
      - "8001:8001"
    depends_on:
      - database
      - client
    env_file:
      - ./envs/addresses.env
      - ./envs/alerts-schema.env
      - ./envs/database-schema.env
      - ./envs/secrets.env
  client:
    build: ./src/client
    ports:
      - "8002:8002"
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./envs/addresses.env
      - ./envs/alerts-schema.env
      - ./envs/database-schema.env
      - ./envs/secrets.env
  database:
    build: ./src/database
    ports:
      - "8000:8000"
    volumes:
      - /Users/jakejack/Documents/JayJayAlerts/data/:/data/
    env_file:
      - ./envs/addresses.env
      - ./envs/alerts-schema.env
      - ./envs/database-schema.env
      - ./envs/secrets.env
  website:
    build: ./src/website
    ports:
      - "3001:3001"
    env_file:
      - ./envs/addresses.env
      - ./envs/alerts-schema.env
      - ./envs/database-schema.env
      - ./envs/secrets.env
