name: Lint

on: push

jobs:
  lint:
    name: "Lint application"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository code
        uses: actions/checkout@v2
      - run: npm run build
        name: Build shared image
      - run: docker run --env SEC_CLIENTID --env SEC_CLIENTSECRET --entrypoint /.github/scripts/entrypoint.sh jayjayalerts
        name: Lint bot node
        env:
          SEC_CLIENTID: ${{ secrets.SEC_CLIENTID }}
          SEC_CLIENTSECRET: ${{ secrets.SEC_CLIENT }}
