name: Lint

on: push

jobs:
  lint_bot:
    name: "Lint bot node"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository code
        uses: actions/checkout@v2
      - run: docker build . -t jayjayalerts
        name: Build shared image
      - run: docker run --env SEC_CLIENTID --env SEC_CLIENTSECRET --entrypoint "npm run lint" jayjayalerts
        name: Lint bot node
